### ISSUE TITLE
APM package not found

### ISSUE THREAD

**Issue by FPierre** [fsblemos/lint-sass-vue#1]
Awesome tool, but APM installation failed:

```bash
$ apm install sass-lint-vue
Installing sass-lint-vue to /home/pierre/.atom/packages ✗
Request for package information failed: Not Found
```

**Comment by fsblemos** [comment]
Hi @FPierre!

The readme was wrong, sorry. Please, try `apm install lint-sass-vue` instead.
Tkank you for your feedback.

**Comment by FPierre** [comment]
It's work now!
