### ISSUE TITLE
It doesn't work !

### ISSUE THREAD

**Issue by zhouyu1993** [fsblemos/lint-sass-vue#2]
I install **linter-sass-lint**, this will lint [.scss] files.

Then I install **lint-sass-vue**, this does't lint [.vue] files.

**Comment by fsblemos** [comment]
Hi @zhouyu1993.

Did you configure .sass-lint.yml in your repository and the template of your file is like in the instructions?
Please, provide more details or paste the file you are trying to lint so that I can help you.

Thank you :)

**Comment by zhouyu1993** [comment]
😭I know what's wrong .
My .sass-lint.yml didn't include '**/*.vue'  .

**Comment by fsblemos** [comment]
:smile:
